project:
  type: website
  output-dir: docs

website:
  title: "kanishka manna"
  search: false
  navbar:
    right:
      - href: about.qmd
        text: about me
      - href: CV/kanishkamanna_CV.pdf
        text: cv
  page-footer:
    left: "© 2023 Kanishka Manna"
    right: 
       - icon: linkedin
         href: https://www.linkedin.com/in/kanishka-manna/
       - icon: github
         href: https://github.com/kanishkamanna
       - text: <i class="ai ai-orcid" role="img"></i>
         href: https://orcid.org/0000-0003-3927-5004
       - text: <i class="ai ai-google-scholar" role="img"></i>
         href: https://scholar.google.com/citations?user=jc_Lzu4AAAAJ&hl=en
       - icon: envelope
         href: mailto:kanishka.manna@gmail.com

format:
  html:
    page-layout: full
    sidebar: false
    theme: 
       - cosmo
       - brown-theme.scss
    css: 
       - styles.css
       - academicons.css
    toc: true

editor: visual

