project:
  type: website
  output-dir: docs

website:
  #site-url: https://kanishkamanna.github.io
  title: "kanishka manna"
  navbar:
    right:
      - href: index.qmd
        text: home
      - href: about.qmd
        text: bio
      - href: CV/kanishkamanna_CV.pdf
        text: cv
  page-footer:
    background: light
    left: Copyright 2023, Kanishka Manna
    

format:
  html:
    page-layout: full
    sidebar: false
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

