---
title: ""
title-block-banner: true
---

Hello! 

I am a Bioinformatics scientist and an incoming Postdoctoral Scholar in the [Nevada Bioinformatics Center](https://www.unr.edu/bioinformatics) at the [University of Nevada, Reno](https://www.unr.edu). I completed my Ph.D. in Bioinformatics in [Dr. Stephanie Byrum’s lab](https://github.com/ByrumLab) at the [Univesity of Arkansas, Little Rock (UALR)](https://ualr.edu/bioinformatics/) and the [University of Arkansas for Medical Sciences (UAMS)](https://gradschool.uams.edu/prospective-students/programs/master-of-science-ph-d-in-bioinformatics) in the US. Before pursuing doctoral studies, I earned my bachelor’s and master’s degrees in Microbiology from [Vijaygarh Jyotish Ray College](https://www.vijaygarhjrcollege.com) (affiliated to the University of Calcutta) in India. Transitioning from experimental lab to data science role was not an easy feat, but I am glad that I made the journey! Back in 2017, I attended a seminar on cancer presented by Dr. Mary-Claire King, it was there I got acquainted with genomics and bioinformatics. This intensified my passion for research in biochemistry and motivated me to dive into the world of computational biology and bioinformatics, specifically the analysis of next-generation sequencing (NGS) based multi-omics data.

As part of my doctoral research, I developed a reproducible proteogenomics pipeline that can generate custom protein sequence databases by integrating, curating and annotating multi-omics (genomics, transcriptomics) data. These custom protein sequence databases can then be leveraged primarily to detect novel proteoforms (protein isoforms) downstream in-conjunction with proteomics data. My research goals are to analyze various -omics data (genomics, transcriptomics, proteomics and metabolomics) and developing new scientific software and methods for analyzing these kinds of data. This means I'm dependent on others sharing their data, and proudly consider myself a research parasite. I believe in open science, open source software and reproducible data analysis.

I feel very fortunate to be doing so many things that I love a lot right now. That includes my work, but also spending a lot of time outdoors. Mountains have always hold a special place in my heart ever since my father introduce me to hiking in the Himalayas. And over the years, I have piqued new interests in backcountry camping, rock climbing along with hiking; my love for these sports keep growing stronger. Most of my free time is now spent on trails. Other than spending time outdoors, you’ll find me illustrating using watercolor techniques.

This website is an introduction to who I am, providing a clear picture of my background and research. 

Thank you ! 😊
\
\
Best regards,\
Kanishka Manna

